"""
waste_sorter.py  -  Raspberry Pi Vision Controller
====================================================
6-DOF Robot Arm  |  Waste Classification & Sorting
----------------------------------------------------

FOLDER STRUCTURE (all in the same folder):
    waste_sorter.py
    best.pt
    homography.npy        <- generated by calibrate_homography.py

FIRMWARE PROTOCOL (Demo_march_24_fixed.ino):
    Pi sends:
        PICK <class> <x_cm> <y_cm> <bbox_w> <bbox_h>
        GRIP
        RELEASE
        HOME

    ItsyBitsy replies:
        DONE
        ERROR

WORKSPACE LIMITS (from ik_table.h):
    x = 8.5 .. 13.5 cm
    y = 0.6 ..  4.4 cm

STATE MACHINE:
    IDLE -> CONFIRMING -> MOVING -> GRIPPING -> DEPOSITING -> IDLE

HOW TO RUN:
    1. Run calibrate_homography.py once to generate homography.npy
    2. Adjust BIN_ANGLES to match your physical bin positions
    3. python waste_sorter.py
"""

from __future__ import annotations

import cv2
import numpy as np
import serial
import time
import logging
import sys
import os
import threading
import collections
from dataclasses import dataclass, field
from enum import Enum, auto
from ultralytics import YOLO


# ══════════════════════════════════════════════════════════════════
#  CONFIGURATION
# ══════════════════════════════════════════════════════════════════

MODEL_PATH        = "best.pt"
HOMOGRAPHY_FILE   = "homography.npy"

CONFIDENCE_THRESHOLD = 0.25
NMS_IOU              = 0.45
INFER_SIZE           = 320

CAMERA_INDEX  = 0        # 0 = built-in | 1 = USB Logitech
FRAME_WIDTH   = 640
FRAME_HEIGHT  = 480

SERIAL_PORT     = "COM5"
SERIAL_BAUDRATE = 9600
SERIAL_TIMEOUT  = 40

CONFIRM_FRAMES_NEEDED = 3
CONFIRM_MISS_ALLOWED  = 4
DISAPPEAR_THRESHOLD   = 5

WS_X_MIN, WS_X_MAX = 8.5, 13.5
WS_Y_MIN, WS_Y_MAX = 0.6,  4.4

BIN_ANGLES = {
    "plastic":   60,
    "paper":     90,
    "cardboard": 120,
    "general":   90,
}

WASTE_CLASSES = {
    0: {"name": "general",   "bin": "landfill"},
    1: {"name": "paper",     "bin": "paper"},
    2: {"name": "plastic",   "bin": "plastic"},
    3: {"name": "cardboard", "bin": "cardboard"},
}

CLASS_COLORS = {
    "general":   (128, 128, 128),
    "paper":     (200, 200, 255),
    "plastic":   (255,  80,  80),
    "cardboard": ( 50, 165, 255),
}


# ══════════════════════════════════════════════════════════════════
#  LOGGING
# ══════════════════════════════════════════════════════════════════

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("waste_sorter.log"),
    ],
)
logger = logging.getLogger("WasteSorter")


# ══════════════════════════════════════════════════════════════════
#  STATE MACHINE
# ══════════════════════════════════════════════════════════════════

class State(Enum):
    IDLE        = auto()
    CONFIRMING  = auto()
    MOVING      = auto()
    GRIPPING    = auto()
    DEPOSITING  = auto()


# ══════════════════════════════════════════════════════════════════
#  DATA CLASSES
# ══════════════════════════════════════════════════════════════════

@dataclass
class Detection:
    class_id:   int
    class_name: str
    bin_name:   str
    confidence: float
    cx:         int
    cy:         int
    bbox_w:     int
    bbox_h:     int
    x_cm:       float
    y_cm:       float

@dataclass
class Stats:
    picks_attempted: int = 0
    picks_succeeded: int = 0
    picks_failed:    int = 0
    counts: dict = field(default_factory=lambda: collections.defaultdict(int))


# ══════════════════════════════════════════════════════════════════
#  HOMOGRAPHY / COORDINATE CONVERSION
# ══════════════════════════════════════════════════════════════════

def load_homography(path: str) -> np.ndarray | None:
    if not os.path.exists(path):
        logger.warning("Homography file '%s' not found.", path)
        logger.warning("Run calibrate_homography.py first for accurate coordinates.")
        return None
    H = np.load(path)
    logger.info("Homography loaded from '%s'  shape=%s", path, H.shape)
    return H


def pixel_to_cm(cx: int, cy: int, H: np.ndarray | None) -> tuple[float, float]:
    if H is not None:
        pt     = np.array([[[float(cx), float(cy)]]], dtype=np.float32)
        result = cv2.perspectiveTransform(pt, H)
        return round(float(result[0][0][0]), 2), round(float(result[0][0][1]), 2)
    x_cm = 11.0 + (cx - FRAME_WIDTH  / 2.0) * 0.034
    y_cm =  2.5 + (cy - FRAME_HEIGHT / 2.0) * 0.034
    return round(x_cm, 2), round(y_cm, 2)


# ══════════════════════════════════════════════════════════════════
#  DETECTION  (Fixed_vision engine — stream=True)
# ══════════════════════════════════════════════════════════════════

def draw_box(img, xyxy, label: str, color=(0, 255, 0)):
    x1, y1, x2, y2 = map(int, xyxy)
    cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
    cv2.putText(img, label, (x1, max(0, y1 - 8)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2)


def detect_best(frame: np.ndarray, model: YOLO,
                H: np.ndarray | None) -> Detection | None:
    """
    Run YOLO on one frame using stream=True.
    Returns the highest-confidence detection regardless of workspace range.
    Draws boxes on the frame in-place.
    """
    results = model.predict(
        frame,
        conf=CONFIDENCE_THRESHOLD,
        iou=NMS_IOU,
        imgsz=INFER_SIZE,
        verbose=False,
        stream=True,
    )
    r = next(results, None)

    if r is None or r.boxes is None or len(r.boxes) == 0:
        return None

    xyxys = r.boxes.xyxy.cpu().numpy()
    confs = r.boxes.conf.cpu().numpy()
    clss  = r.boxes.cls.cpu().numpy().astype(int)

    best: Detection | None = None
    best_conf = 0.0

    for xyxy, conf, c in zip(xyxys, confs, clss):
        class_id   = int(c)
        final_conf = float(conf)

        info = WASTE_CLASSES.get(class_id)
        if info is None:
            continue

        class_name = info["name"]
        bin_name   = info["bin"]
        color      = CLASS_COLORS.get(class_name, (0, 255, 0))

        x1, y1, x2, y2 = map(int, xyxy)
        cx     = (x1 + x2) // 2
        cy     = (y1 + y2) // 2
        bbox_w = x2 - x1
        bbox_h = y2 - y1
        x_cm, y_cm = pixel_to_cm(cx, cy, H)

        # Draw box and labels
        draw_box(frame, xyxy, f"{class_name} {final_conf:.2f}", color)
        cv2.circle(frame, (cx, cy), 5, (0, 0, 255), -1)
        cv2.putText(frame, f"({x_cm:.1f},{y_cm:.1f}) cm",
                    (x1, y2 + 16), cv2.FONT_HERSHEY_SIMPLEX,
                    0.38, (0, 210, 255), 1)
        cv2.putText(frame, f"bin: {bin_name}",
                    (x1, y2 + 30), cv2.FONT_HERSHEY_SIMPLEX,
                    0.36, (180, 180, 180), 1)

        if final_conf > best_conf:
            best_conf = final_conf
            best = Detection(
                class_id=class_id, class_name=class_name, bin_name=bin_name,
                confidence=final_conf, cx=cx, cy=cy,
                bbox_w=bbox_w, bbox_h=bbox_h,
                x_cm=x_cm, y_cm=y_cm,
            )

    return best


# ══════════════════════════════════════════════════════════════════
#  SERIAL COMMUNICATION
# ══════════════════════════════════════════════════════════════════

class ArmComm:
    """Thread-safe serial interface to Demo_march_24_fixed.ino."""

    def __init__(self, port: str, baudrate: int, timeout: int):
        self.port      = port
        self.baudrate  = baudrate
        self.timeout   = timeout
        self.conn      = None
        self.connected = False
        self._lock     = threading.Lock()
        self._connect()

    def _connect(self):
        try:
            self.conn = serial.Serial(
                port=self.port, baudrate=self.baudrate,
                timeout=1, write_timeout=1,
            )
            time.sleep(2)
            self.conn.reset_input_buffer()
            self.connected = True
            logger.info("ArmComm: connected on %s @ %d baud", self.port, self.baudrate)
        except serial.SerialException as exc:
            logger.error("ArmComm: connection failed: %s", exc)
            self.connected = False

    def send(self, command: str) -> bool:
        if not self.connected or not self.conn or not self.conn.is_open:
            logger.warning("ArmComm: not connected — dropped: %s", command.strip())
            return False
        payload = command.strip() + "\n"
        try:
            with self._lock:
                self.conn.write(payload.encode())
            logger.info("TX >> %s", payload.strip())
            return True
        except serial.SerialException as exc:
            logger.error("ArmComm: write error: %s", exc)
            return False

    def pick(self, class_name: str, x_cm: float, y_cm: float,
             bbox_w: int, bbox_h: int) -> bool:
        return self.send(
            f"PICK {class_name.upper()} {x_cm:.2f} {y_cm:.2f} {bbox_w} {bbox_h}"
        )

    def move(self, x_cm: float, y_cm: float) -> bool:
        return self.send(f"MOVE {x_cm:.2f} {y_cm:.2f}")

    def grip(self) -> bool:
        return self.send("GRIP")

    def release(self) -> bool:
        return self.send("RELEASE")

    def home(self) -> bool:
        return self.send("HOME")

    def wait_done(self, timeout_override: int | None = None) -> bool:
        deadline = time.time() + (timeout_override or self.timeout)
        while time.time() < deadline:
            try:
                if self.conn and self.conn.in_waiting:
                    line = (self.conn.readline()
                            .decode(errors="replace").strip().upper())
                    logger.info("RX << %s", line)
                    if "DONE"  in line: return True
                    if "ERROR" in line:
                        logger.error("ArmComm: firmware ERROR")
                        return False
                time.sleep(0.05)
            except serial.SerialException as exc:
                logger.error("ArmComm: read error: %s", exc)
                return False
        logger.error("ArmComm: timed out waiting for DONE")
        return False

    def close(self):
        if self.conn and self.conn.is_open:
            self.conn.close()
            logger.info("ArmComm: connection closed")


# ══════════════════════════════════════════════════════════════════
#  FEEDBACK LOOP  (monitor only — no movement commands)
# ══════════════════════════════════════════════════════════════════

def run_feedback_loop(
    camera:          cv2.VideoCapture,
    camera_lock:     threading.Lock,
    model:           YOLO,
    arm:             ArmComm,
    target_class_id: int,
    stop_event:      threading.Event,
    reached_event:   threading.Event,
):
    """
    Runs AFTER the arm has reached the pick position (wait_done returned).
    Does NOT send movement commands — arm is already in position.
    Only watches for the object to disappear, then sends GRIP.
    """
    disappear_count = 0
    logger.info("Feedback loop started — monitoring class_id %d", target_class_id)

    while not stop_event.is_set():
        with camera_lock:
            ret, frame = camera.read()

        if not ret:
            logger.warning("Feedback loop: failed to read frame.")
            time.sleep(0.1)
            continue

        results = model.predict(
            frame,
            conf=CONFIDENCE_THRESHOLD,
            iou=NMS_IOU,
            imgsz=INFER_SIZE,
            verbose=False,
            stream=True,
        )
        r = next(results, None)

        object_visible = False
        if r is not None and r.boxes is not None and len(r.boxes) > 0:
            for conf, c in zip(
                r.boxes.conf.cpu().numpy(),
                r.boxes.cls.cpu().numpy().astype(int),
            ):
                if int(c) == target_class_id and float(conf) >= CONFIDENCE_THRESHOLD:
                    object_visible = True
                    break

        if object_visible:
            disappear_count = 0
            logger.debug("Feedback: object still visible")
        else:
            disappear_count += 1
            logger.debug("Feedback: object missing (%d/%d)",
                         disappear_count, DISAPPEAR_THRESHOLD)
            if disappear_count >= DISAPPEAR_THRESHOLD:
                logger.info("Feedback: object gone — sending GRIP")
                arm.grip()
                reached_event.set()
                break

        time.sleep(0.1)

    logger.info("Feedback loop stopped.")


# ══════════════════════════════════════════════════════════════════
#  DEPOSIT SEQUENCE
# ══════════════════════════════════════════════════════════════════

def deposit_sequence(arm: ArmComm, target: Detection, stats: Stats) -> bool:
    """Move to deposit position, release, return home."""
    logger.info("Depositing '%s'", target.class_name)

    X_DEPOSIT = 11.0   # cm — tune for your setup
    Y_DEPOSIT  =  2.0  # cm — tune for your setup

    ok = arm.move(X_DEPOSIT, Y_DEPOSIT)
    if ok:
        ok = arm.wait_done(timeout_override=15)

    if ok:
        arm.release()
        time.sleep(0.5)
        stats.picks_succeeded += 1
        stats.counts[target.class_name] += 1
        logger.info("Deposit OK. Counts: %s", dict(stats.counts))
    else:
        logger.error("Deposit move failed — releasing in place.")
        arm.release()
        stats.picks_failed += 1

    arm.home()
    arm.wait_done(timeout_override=15)
    return ok


# ══════════════════════════════════════════════════════════════════
#  HUD
# ══════════════════════════════════════════════════════════════════

_STATE_COLORS = {
    State.IDLE:       (0, 200,   0),
    State.CONFIRMING: (0, 220, 255),
    State.MOVING:     (0, 165, 255),
    State.GRIPPING:   (0, 100, 255),
    State.DEPOSITING: (0,  60, 255),
}

def draw_hud(frame, state, fps, confirm_count, target, stats, homography_ok):
    h, w = frame.shape[:2]
    color = _STATE_COLORS.get(state, (255, 255, 255))

    cv2.rectangle(frame, (0, 0), (w, 46), (20, 20, 20), -1)
    cv2.putText(frame, f"State: {state.name}",
                (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)
    cv2.putText(frame, f"FPS {fps:.1f}",
                (w - 88, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (200, 200, 200), 1)

    if not homography_ok:
        cv2.putText(frame, "! NO HOMOGRAPHY — run calibrate_homography.py",
                    (10, 62), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 60, 255), 1)

    if target and state in (State.IDLE, State.CONFIRMING):
        info = (f"{target.class_name.upper()}  conf={target.confidence:.2f}"
                f"  ({target.x_cm:.1f},{target.y_cm:.1f}) cm"
                f"  bin={target.bin_name}")
        cv2.putText(frame, info, (10, 68),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 255, 120), 1)

    if state == State.CONFIRMING:
        ratio = min(confirm_count / CONFIRM_FRAMES_NEEDED, 1.0)
        bar_w = int((w - 20) * ratio)
        cv2.rectangle(frame, (10, 76), (w - 10, 86), (50, 50, 50), -1)
        cv2.rectangle(frame, (10, 76), (10 + bar_w, 86), (0, 220, 255), -1)
        cv2.putText(frame, f"Confirming {confirm_count}/{CONFIRM_FRAMES_NEEDED}",
                    (10, 100), cv2.FONT_HERSHEY_SIMPLEX, 0.44, (0, 220, 255), 1)

    px = w - 178
    cv2.rectangle(frame, (px, 50), (w, 140), (20, 20, 20), -1)
    cv2.putText(frame, f"Picks: {stats.picks_attempted}",
                (px + 6, 68),  cv2.FONT_HERSHEY_SIMPLEX, 0.42, (200, 200, 200), 1)
    cv2.putText(frame, f"OK:    {stats.picks_succeeded}",
                (px + 6, 84),  cv2.FONT_HERSHEY_SIMPLEX, 0.42, (0, 200, 80), 1)
    cv2.putText(frame, f"Fail:  {stats.picks_failed}",
                (px + 6, 100), cv2.FONT_HERSHEY_SIMPLEX, 0.42, (80, 80, 255), 1)
    y = 116
    for name, n in list(stats.counts.items())[:2]:
        cv2.putText(frame, f"{name}: {n}",
                    (px + 6, y), cv2.FONT_HERSHEY_SIMPLEX, 0.38, (160, 160, 160), 1)
        y += 14

    cv2.rectangle(frame, (0, h - 28), (w, h), (20, 20, 20), -1)
    cv2.putText(frame, "[H] home  [G] grip  [R] release  [Q] quit",
                (10, h - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.42, (140, 140, 140), 1)


# ══════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════

def main():
    logger.info("=" * 60)
    logger.info("  Waste Sorter  -  6-DOF Robot Arm Vision Controller")
    logger.info("=" * 60)

    H = load_homography(HOMOGRAPHY_FILE)
    homography_ok = H is not None

    logger.info("Loading YOLO model: %s", MODEL_PATH)
    try:
        model = YOLO(MODEL_PATH)
        logger.info("Model ready. Classes: %s", model.names)
    except Exception as exc:
        logger.critical("Failed to load model: %s", exc)
        return

    logger.info("Opening camera index=%d", CAMERA_INDEX)
    camera = cv2.VideoCapture(CAMERA_INDEX)
    camera.set(cv2.CAP_PROP_FRAME_WIDTH,  FRAME_WIDTH)
    camera.set(cv2.CAP_PROP_FRAME_HEIGHT, FRAME_HEIGHT)
    camera.set(cv2.CAP_PROP_BUFFERSIZE, 1)

    if not camera.isOpened():
        logger.critical("Camera not found. Change CAMERA_INDEX.")
        return
    logger.info("Camera ready: %dx%d", FRAME_WIDTH, FRAME_HEIGHT)

    camera_lock = threading.Lock()

    arm = ArmComm(SERIAL_PORT, SERIAL_BAUDRATE, SERIAL_TIMEOUT)
    if not arm.connected:
        logger.warning("Arm not connected. Commands will be logged only.")

    state         = State.IDLE
    target        = None
    confirm_count = 0
    confirm_miss  = 0
    stats         = Stats()

    stop_event    = threading.Event()
    reached_event = threading.Event()
    fb_thread     = None

    frame_count = 0
    fps_time    = time.time()
    fps         = 0.0

    logger.info("System ready. Auto-pick ON (%d confirm frames).", CONFIRM_FRAMES_NEEDED)
    logger.info("Controls: [H] home  [G] grip  [R] release  [Q] quit")
    logger.info("-" * 60)

    try:
        while True:

            with camera_lock:
                ret, frame = camera.read()
            if not ret:
                logger.error("Camera read failed — exiting")
                break

            frame_count += 1
            if frame_count % 30 == 0:
                now      = time.time()
                fps      = 30.0 / max(now - fps_time, 1e-6)
                fps_time = now

            # ── MOVING: feedback loop sent GRIP ──────────────────
            if state == State.MOVING and reached_event.is_set():
                state = State.GRIPPING
                stop_event.set()
                if fb_thread:
                    fb_thread.join(timeout=2.0)
                fb_thread = None
                stats.picks_attempted += 1
                logger.info("Object reached. Waiting for grip + lift...")

                grip_done = arm.wait_done(timeout_override=20)

                if grip_done:
                    state  = State.DEPOSITING
                    dep_ok = deposit_sequence(arm, target, stats)
                    if not dep_ok:
                        stats.picks_failed += 1
                else:
                    logger.error("Grip sequence failed.")
                    stats.picks_failed += 1
                    arm.release()
                    arm.home()
                    arm.wait_done(timeout_override=15)

                state         = State.IDLE
                target        = None
                confirm_count = 0
                confirm_miss  = 0
                stop_event.clear()
                reached_event.clear()

            # ── IDLE / CONFIRMING: run detection ─────────────────
            if state in (State.IDLE, State.CONFIRMING):
                best = detect_best(frame, model, H)

                if best:
                    if state == State.IDLE:
                        state = State.CONFIRMING

                    confirm_count += 1
                    confirm_miss   = 0
                    target         = best

                    # Auto-pick trigger
                    if confirm_count >= CONFIRM_FRAMES_NEEDED:
                        logger.info(
                            "Auto-pick: %s  conf=%.2f  (%.2f, %.2f) cm  bbox=(%d,%d)",
                            target.class_name, target.confidence,
                            target.x_cm, target.y_cm,
                            target.bbox_w, target.bbox_h,
                        )

                        sent = arm.pick(
                            target.class_name,
                            target.x_cm, target.y_cm,
                            target.bbox_w, target.bbox_h,
                        )

                        if sent:
                            state         = State.MOVING
                            confirm_count = 0

                            # Wait for arm to reach position before
                            # starting the feedback monitor
                            logger.info("Waiting for arm to reach pick position...")
                            arm_ok = arm.wait_done(timeout_override=20)

                            if arm_ok:
                                stop_event.clear()
                                reached_event.clear()
                                fb_thread = threading.Thread(
                                    target=run_feedback_loop,
                                    args=(
                                        camera, camera_lock, model, arm,
                                        target.class_id,
                                        stop_event, reached_event,
                                    ),
                                    daemon=True,
                                )
                                fb_thread.start()
                                logger.info("Arm in position. Feedback loop watching for grip trigger.")
                            else:
                                logger.error("Arm did not reach position — aborting.")
                                state         = State.IDLE
                                confirm_count = 0
                        else:
                            logger.error("PICK send failed — aborting.")
                            state         = State.IDLE
                            confirm_count = 0

                else:
                    # No detection this frame
                    confirm_miss += 1
                    if confirm_miss >= CONFIRM_MISS_ALLOWED:
                        if state == State.CONFIRMING:
                            logger.debug("Confirmation lost — back to IDLE")
                        state         = State.IDLE
                        confirm_count = 0
                        confirm_miss  = 0
                        target        = None

            # ── HUD + display ────────────────────────────────────
            draw_hud(frame, state, fps, confirm_count, target, stats, homography_ok)
            cv2.imshow("Waste Sorter - 6DOF Robot Vision", frame)

            key = cv2.waitKey(1) & 0xFF
            if key == ord("q"):
                logger.info("Quit requested.")
                break
            elif key == ord("h") and state == State.IDLE:
                arm.home()
            elif key == ord("g") and state == State.IDLE:
                arm.grip()
            elif key == ord("r") and state == State.IDLE:
                arm.release()

    except KeyboardInterrupt:
        logger.info("Interrupted by user (Ctrl+C).")

    finally:
        logger.info("Shutting down...")
        stop_event.set()
        if fb_thread and fb_thread.is_alive():
            fb_thread.join(timeout=2.0)
        arm.release()
        arm.home()
        camera.release()
        cv2.destroyAllWindows()
        arm.close()
        logger.info(
            "Final stats -> attempted=%d  OK=%d  fail=%d  by_class=%s",
            stats.picks_attempted, stats.picks_succeeded,
            stats.picks_failed, dict(stats.counts),
        )
        logger.info("Shutdown complete.")


if __name__ == "__main__":
    main()
